/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class scalallvm_LLVM_00024 */

#ifndef _Included_scalallvm_LLVM_00024
#define _Included_scalallvm_LLVM_00024
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ContextCreate
 * Signature:  ()J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_ContextCreate
  (JNIEnv *, jobject);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ContextDispose
 * Signature:  (J)V
 */
JNIEXPORT void JNICALL Java_scalallvm_LLVM_00024_ContextDispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     DataLayoutABIAlignment
 * Signature:  (JJ)I
 */
JNIEXPORT jint JNICALL Java_scalallvm_LLVM_00024_DataLayoutABIAlignment
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     DataLayoutBitWidth
 * Signature:  (JJ)I
 */
JNIEXPORT jint JNICALL Java_scalallvm_LLVM_00024_DataLayoutBitWidth
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     DataLayoutDescription
 * Signature:  (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_scalallvm_LLVM_00024_DataLayoutDescription
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     DataLayoutFromTargetMachine
 * Signature:  (J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_DataLayoutFromTargetMachine
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     DataLayoutHasPaddingBits
 * Signature:  (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_scalallvm_LLVM_00024_DataLayoutHasPaddingBits
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     DataLayoutIndexOfElementContaining
 * Signature:  (JIJ)I
 */
JNIEXPORT jint JNICALL Java_scalallvm_LLVM_00024_DataLayoutIndexOfElementContaining
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     DataLayoutIsDefault
 * Signature:  (J)Z
 */
JNIEXPORT jboolean JNICALL Java_scalallvm_LLVM_00024_DataLayoutIsDefault
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     DataLayoutOffsetOfElement
 * Signature:  (JIJ)I
 */
JNIEXPORT jint JNICALL Java_scalallvm_LLVM_00024_DataLayoutOffsetOfElement
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     DataLayoutPreferredAlignment
 * Signature:  (JJ)I
 */
JNIEXPORT jint JNICALL Java_scalallvm_LLVM_00024_DataLayoutPreferredAlignment
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     DataLayoutStorgeSize
 * Signature:  (JJ)I
 */
JNIEXPORT jint JNICALL Java_scalallvm_LLVM_00024_DataLayoutStorgeSize
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ModuleCreateWithNameInContext
 * Signature:  (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_ModuleCreateWithNameInContext
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ModuleDescription
 * Signature:  (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_scalallvm_LLVM_00024_ModuleDescription
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ModuleGetDataLyout
 * Signature:  (J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_ModuleGetDataLyout
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ModuleGetName
 * Signature:  (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_scalallvm_LLVM_00024_ModuleGetName
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ModuleGetTriple
 * Signature:  (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_scalallvm_LLVM_00024_ModuleGetTriple
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ModuleDispose
 * Signature:  (J)V
 */
JNIEXPORT void JNICALL Java_scalallvm_LLVM_00024_ModuleDispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ModuleSetName
 * Signature:  (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_scalallvm_LLVM_00024_ModuleSetName
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ModuleSetTriple
 * Signature:  (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_scalallvm_LLVM_00024_ModuleSetTriple
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     InstructionBuilderCreateInContext
 * Signature:  (J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_InstructionBuilderCreateInContext
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     InstructionBuilderDispose
 * Signature:  (J)V
 */
JNIEXPORT void JNICALL Java_scalallvm_LLVM_00024_InstructionBuilderDispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     InstructionBuilderGetInsertionBlock
 * Signature:  (J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_InstructionBuilderGetInsertionBlock
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     InstructionBuilderMakeAlloca
 * Signature:  (JJIJLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_InstructionBuilderMakeAlloca
  (JNIEnv *, jobject, jlong, jlong, jint, jlong, jstring);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     InstructionBuilderMakeBr
 * Signature:  (JJ)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_InstructionBuilderMakeBr
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     InstructionBuilderMakeConditionalBr
 * Signature:  (JJJJ)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_InstructionBuilderMakeConditionalBr
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     InstructionBuilderMakeGEP
 * Signature:  (JJJ[JLjava/lang/String;Z)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_InstructionBuilderMakeGEP
  (JNIEnv *, jobject, jlong, jlong, jlong, jlongArray, jstring, jboolean);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     InstructionBuilderMakeLoad
 * Signature:  (JJJZLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_InstructionBuilderMakeLoad
  (JNIEnv *, jobject, jlong, jlong, jlong, jboolean, jstring);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     InstructionBuilderMakeReturn
 * Signature:  (JJ)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_InstructionBuilderMakeReturn
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     InstructionBuilderMakeStore
 * Signature:  (JJJZ)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_InstructionBuilderMakeStore
  (JNIEnv *, jobject, jlong, jlong, jlong, jboolean);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     InstructionBuilderMakeStructGEP
 * Signature:  (JJJILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_InstructionBuilderMakeStructGEP
  (JNIEnv *, jobject, jlong, jlong, jlong, jint, jstring);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     InstructionBuilderMakeSwitch
 * Signature:  (JJJ[J[J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_InstructionBuilderMakeSwitch
  (JNIEnv *, jobject, jlong, jlong, jlong, jlongArray, jlongArray);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     InstructionBuilderMakeTruncTo
 * Signature:  (JJJLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_InstructionBuilderMakeTruncTo
  (JNIEnv *, jobject, jlong, jlong, jlong, jstring);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     InstructionBuilderMakeUnreachable
 * Signature:  (J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_InstructionBuilderMakeUnreachable
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     InstructionBuilderPositionAtEndOfBlock
 * Signature:  (JJ)V
 */
JNIEXPORT void JNICALL Java_scalallvm_LLVM_00024_InstructionBuilderPositionAtEndOfBlock
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     TypeDescription
 * Signature:  (JZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_scalallvm_LLVM_00024_TypeDescription
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     TypeGetKind
 * Signature:  (J)B
 */
JNIEXPORT jbyte JNICALL Java_scalallvm_LLVM_00024_TypeGetKind
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ArrayTypeCreateInContext
 * Signature:  (IJJ)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_ArrayTypeCreateInContext
  (JNIEnv *, jobject, jint, jlong, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ArrayTypeCount
 * Signature:  (J)I
 */
JNIEXPORT jint JNICALL Java_scalallvm_LLVM_00024_ArrayTypeCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ArrayTypeElement
 * Signature:  (J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_ArrayTypeElement
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ArrayTypeKind
 * Signature:  ()B
 */
JNIEXPORT jbyte JNICALL Java_scalallvm_LLVM_00024_ArrayTypeKind
  (JNIEnv *, jobject);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     DoubleTypeInContext
 * Signature:  (J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_DoubleTypeInContext
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     DoubleTypeKind
 * Signature:  ()B
 */
JNIEXPORT jbyte JNICALL Java_scalallvm_LLVM_00024_DoubleTypeKind
  (JNIEnv *, jobject);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     FloatTypeInContext
 * Signature:  (J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_FloatTypeInContext
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     FloatTypeKind
 * Signature:  ()B
 */
JNIEXPORT jbyte JNICALL Java_scalallvm_LLVM_00024_FloatTypeKind
  (JNIEnv *, jobject);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     FunctionType
 * Signature:  ([JJ)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_FunctionType
  (JNIEnv *, jobject, jlongArray, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     FunctionTypeKind
 * Signature:  ()B
 */
JNIEXPORT jbyte JNICALL Java_scalallvm_LLVM_00024_FunctionTypeKind
  (JNIEnv *, jobject);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     FunctionTypeParameterAt
 * Signature:  (JI)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_FunctionTypeParameterAt
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     FunctionTypeParameterCount
 * Signature:  (J)I
 */
JNIEXPORT jint JNICALL Java_scalallvm_LLVM_00024_FunctionTypeParameterCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     FunctionTypeReturn
 * Signature:  (J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_FunctionTypeReturn
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     IntTypeInContext
 * Signature:  (IJ)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_IntTypeInContext
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     IntegerTypeKind
 * Signature:  ()B
 */
JNIEXPORT jbyte JNICALL Java_scalallvm_LLVM_00024_IntegerTypeKind
  (JNIEnv *, jobject);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     PointerTypeInContext
 * Signature:  (IJ)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_PointerTypeInContext
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     PointerTypeKind
 * Signature:  ()B
 */
JNIEXPORT jbyte JNICALL Java_scalallvm_LLVM_00024_PointerTypeKind
  (JNIEnv *, jobject);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     PointerTypeGetAddressSpace
 * Signature:  (J)I
 */
JNIEXPORT jint JNICALL Java_scalallvm_LLVM_00024_PointerTypeGetAddressSpace
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     StructTypeCreateNominalInContext
 * Signature:  (Ljava/lang/String;[JZJ)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_StructTypeCreateNominalInContext
  (JNIEnv *, jobject, jstring, jlongArray, jboolean, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     StructTypeCreateStructuralInContext
 * Signature:  ([JZJ)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_StructTypeCreateStructuralInContext
  (JNIEnv *, jobject, jlongArray, jboolean, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     StructTypeGetName
 * Signature:  (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_scalallvm_LLVM_00024_StructTypeGetName
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     StructTypeIsLiteral
 * Signature:  (J)Z
 */
JNIEXPORT jboolean JNICALL Java_scalallvm_LLVM_00024_StructTypeIsLiteral
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     StructTypeIsOpaque
 * Signature:  (J)Z
 */
JNIEXPORT jboolean JNICALL Java_scalallvm_LLVM_00024_StructTypeIsOpaque
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     StructTypeIsPacked
 * Signature:  (J)Z
 */
JNIEXPORT jboolean JNICALL Java_scalallvm_LLVM_00024_StructTypeIsPacked
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     StructTypeKind
 * Signature:  ()B
 */
JNIEXPORT jbyte JNICALL Java_scalallvm_LLVM_00024_StructTypeKind
  (JNIEnv *, jobject);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     StructTypeMemberAt
 * Signature:  (JI)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_StructTypeMemberAt
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     StructTypeMemberCount
 * Signature:  (J)I
 */
JNIEXPORT jint JNICALL Java_scalallvm_LLVM_00024_StructTypeMemberCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     VoidTypeInContext
 * Signature:  (J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_VoidTypeInContext
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     VoidTypeKind
 * Signature:  ()B
 */
JNIEXPORT jbyte JNICALL Java_scalallvm_LLVM_00024_VoidTypeKind
  (JNIEnv *, jobject);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ValueDescription
 * Signature:  (JZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_scalallvm_LLVM_00024_ValueDescription
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ValueGetName
 * Signature:  (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_scalallvm_LLVM_00024_ValueGetName
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ValueGetType
 * Signature:  (J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_ValueGetType
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     AllocaGetAddressSpace
 * Signature:  (J)I
 */
JNIEXPORT jint JNICALL Java_scalallvm_LLVM_00024_AllocaGetAddressSpace
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     AllocaGetAlignment
 * Signature:  (J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_AllocaGetAlignment
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     AllocaGetAllocatedType
 * Signature:  (J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_AllocaGetAllocatedType
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     AllocaGetAllocationCount
 * Signature:  (J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_AllocaGetAllocationCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     AllocaIsStatic
 * Signature:  (J)Z
 */
JNIEXPORT jboolean JNICALL Java_scalallvm_LLVM_00024_AllocaIsStatic
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     AllocaFromValue
 * Signature:  (J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_AllocaFromValue
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     AllocaSetAlignment
 * Signature:  (JJ)V
 */
JNIEXPORT void JNICALL Java_scalallvm_LLVM_00024_AllocaSetAlignment
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     BasicBlockCreateInParent
 * Signature:  (Ljava/lang/String;JJ)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_BasicBlockCreateInParent
  (JNIEnv *, jobject, jstring, jlong, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     BasicBlockGetParent
 * Signature:  (J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_BasicBlockGetParent
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     BranchIsConditional
 * Signature:  (J)Z
 */
JNIEXPORT jboolean JNICALL Java_scalallvm_LLVM_00024_BranchIsConditional
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     BranchGetCondition
 * Signature:  (J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_BranchGetCondition
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     BranchFromValue
 * Signature:  (J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_BranchFromValue
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     BranchSuccessorAt
 * Signature:  (JI)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_BranchSuccessorAt
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ConstantAggregateMemberAt
 * Signature:  (JI)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_ConstantAggregateMemberAt
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ConstantArray
 * Signature:  (J[J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_ConstantArray
  (JNIEnv *, jobject, jlong, jlongArray);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ConstantNullValue
 * Signature:  (J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_ConstantNullValue
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ConstantIntCreate
 * Signature:  (JJZ)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_ConstantIntCreate
  (JNIEnv *, jobject, jlong, jlong, jboolean);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ConstantIntCreateWide
 * Signature:  (JI[JZ)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_ConstantIntCreateWide
  (JNIEnv *, jobject, jlong, jint, jlongArray, jboolean);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ConstantIntGetSExtValue
 * Signature:  (J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_ConstantIntGetSExtValue
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ConstantIntGetZExtValue
 * Signature:  (J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_ConstantIntGetZExtValue
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ConstantDouble
 * Signature:  (JD)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_ConstantDouble
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ConstantPoison
 * Signature:  (J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_ConstantPoison
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ConstantStringInContext
 * Signature:  (Ljava/lang/String;ZJ)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_ConstantStringInContext
  (JNIEnv *, jobject, jstring, jboolean, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ConstantStruct
 * Signature:  (J[J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_ConstantStruct
  (JNIEnv *, jobject, jlong, jlongArray);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ConstantUndefined
 * Signature:  (J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_ConstantUndefined
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     LoadGetAlignment
 * Signature:  (J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_LoadGetAlignment
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     LoadIsVolatile
 * Signature:  (J)Z
 */
JNIEXPORT jboolean JNICALL Java_scalallvm_LLVM_00024_LoadIsVolatile
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     LoadFromValue
 * Signature:  (J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_LoadFromValue
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     LoadSetAlignment
 * Signature:  (JJ)V
 */
JNIEXPORT void JNICALL Java_scalallvm_LLVM_00024_LoadSetAlignment
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     StoreGetAlignment
 * Signature:  (J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_StoreGetAlignment
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     StoreIsVolatile
 * Signature:  (J)Z
 */
JNIEXPORT jboolean JNICALL Java_scalallvm_LLVM_00024_StoreIsVolatile
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     StoreFromValue
 * Signature:  (J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_StoreFromValue
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     StoreSetAlignment
 * Signature:  (JJ)V
 */
JNIEXPORT void JNICALL Java_scalallvm_LLVM_00024_StoreSetAlignment
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     SwitchGetCondition
 * Signature:  (J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_SwitchGetCondition
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     SwitchGetDefaultDestination
 * Signature:  (J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_SwitchGetDefaultDestination
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     SwitchFromValue
 * Signature:  (J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_SwitchFromValue
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     SwitchSuccessorAt
 * Signature:  (JI)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_SwitchSuccessorAt
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     SwitchSuccessorCount
 * Signature:  (J)I
 */
JNIEXPORT jint JNICALL Java_scalallvm_LLVM_00024_SwitchSuccessorCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     FunctionCreateInModule
 * Signature:  (Ljava/lang/String;JBIJ)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_FunctionCreateInModule
  (JNIEnv *, jobject, jstring, jlong, jbyte, jint, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     FunctionBasicBlockEntry
 * Signature:  (J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_FunctionBasicBlockEntry
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     FunctionBasicBlocks
 * Signature:  (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_scalallvm_LLVM_00024_FunctionBasicBlocks
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     FunctionGetByNameInModule
 * Signature:  (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_FunctionGetByNameInModule
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     FunctionParameterAfter
 * Signature:  (JJ)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_FunctionParameterAfter
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     FunctionParameterBegin
 * Signature:  (J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_FunctionParameterBegin
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     FunctionParameterCount
 * Signature:  (J)I
 */
JNIEXPORT jint JNICALL Java_scalallvm_LLVM_00024_FunctionParameterCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     FunctionParameterEnd
 * Signature:  (J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_FunctionParameterEnd
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     FunctionVerifiy
 * Signature:  (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_scalallvm_LLVM_00024_FunctionVerifiy
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     LinkageExternal
 * Signature:  ()B
 */
JNIEXPORT jbyte JNICALL Java_scalallvm_LLVM_00024_LinkageExternal
  (JNIEnv *, jobject);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     DefaultTargetTriple
 * Signature:  ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_scalallvm_LLVM_00024_DefaultTargetTriple
  (JNIEnv *, jobject);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     InitializeTargets
 * Signature:  ()V
 */
JNIEXPORT void JNICALL Java_scalallvm_LLVM_00024_InitializeTargets
  (JNIEnv *, jobject);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     DataLayoutDispose
 * Signature:  (J)V
 */
JNIEXPORT void JNICALL Java_scalallvm_LLVM_00024_DataLayoutDispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     TargetGetName
 * Signature:  (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_scalallvm_LLVM_00024_TargetGetName
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     TargetFromTriple
 * Signature:  (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_TargetFromTriple
  (JNIEnv *, jobject, jstring);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     TargetMachineCreate
 * Signature:  (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_TargetMachineCreate
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     TargetMachineDispose
 * Signature:  (J)V
 */
JNIEXPORT void JNICALL Java_scalallvm_LLVM_00024_TargetMachineDispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ConsumeError
 * Signature:  (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_scalallvm_LLVM_00024_ConsumeError
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
