/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class scalallvm_LLVM_00024 */

#ifndef _Included_scalallvm_LLVM_00024
#define _Included_scalallvm_LLVM_00024
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ContextCreate
 * Signature:  ()J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_ContextCreate
  (JNIEnv *, jobject);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ContextDispose
 * Signature:  (J)V
 */
JNIEXPORT void JNICALL Java_scalallvm_LLVM_00024_ContextDispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ModuleCreateWithNameInContext
 * Signature:  (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_ModuleCreateWithNameInContext
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ModuleDescription
 * Signature:  (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_scalallvm_LLVM_00024_ModuleDescription
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ModuleGetName
 * Signature:  (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_scalallvm_LLVM_00024_ModuleGetName
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ModuleDispose
 * Signature:  (J)V
 */
JNIEXPORT void JNICALL Java_scalallvm_LLVM_00024_ModuleDispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ModuleSetName
 * Signature:  (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_scalallvm_LLVM_00024_ModuleSetName
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     IntTypeInContext
 * Signature:  (IJ)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_IntTypeInContext
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     VoidTypeInContext
 * Signature:  (J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_VoidTypeInContext
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ValueDescription
 * Signature:  (JZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_scalallvm_LLVM_00024_ValueDescription
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ValueGetType
 * Signature:  (J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_ValueGetType
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ConstantNullValue
 * Signature:  (J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_ConstantNullValue
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ConstantIntCreate
 * Signature:  (JJZ)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_ConstantIntCreate
  (JNIEnv *, jobject, jlong, jlong, jboolean);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ConstantIntCreateWide
 * Signature:  (JI[JZ)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_ConstantIntCreateWide
  (JNIEnv *, jobject, jlong, jint, jlongArray, jboolean);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ConstantIntGetSExtValue
 * Signature:  (J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_ConstantIntGetSExtValue
  (JNIEnv *, jobject, jlong);

/*
 * Class:      scalallvm_LLVM_00024
 * Method:     ConstantIntGetZExtValue
 * Signature:  (J)J
 */
JNIEXPORT jlong JNICALL Java_scalallvm_LLVM_00024_ConstantIntGetZExtValue
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
